### ISSUE TITLE
Update this repo to reflect actual blog content

### ISSUE THREAD

**Issue by iacore** [n0-computer/n0.computer#10]
I was reading https://www.iroh.computer/blog/iroh-dns, and the link "existing prototype" (at the page end) is broken.

I wonder if the blog can be made open-source so people send PRs to fix typos like this.

**Comment by dignifiedquire** [comment]
the blog is open source in this repo: https://github.com/n0-computer/iroh.computer/tree/main/src/app/blog

**Comment by iacore** [comment]
oh, didn't saw it back then. Thanks.
